version: "3.9"

services:
  simple-weather-api:
    image: simple-weather-api:latest
    container_name: simple-weather-api
    ports:
      - "5000:5000"
    restart: always
    environment:
      - OPENWEATHER_API_KEY